name: Release Changelog

on:
  push:
    branches:
      - release

permissions:
  contents: write
  pull-requests: write

jobs:
  release-changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          release-type: node
          package-name: ariadnes-thread
          changelog-types: |
            [
              {"type":"feat","section":"Features","hidden":false},
              {"type":"fix","section":"Bug Fixes","hidden":false},
              {"type":"docs","section":"Documentation","hidden":true},
              {"type":"perf","section":"Performance","hidden":false},
              {"type":"refactor","section":"Code Refactoring","hidden":true}
            ]
